class Templates:
    NotAnyMessage = '$var cannot be empty (should contain at least one element).'
    NotEqualMessage = 'Equality precondition not met.'
    NotNullMessage = '$var cannot be Null.'
    NotGreaterThanMessage = "$var cannot be greater than $value."
    NotLessThanMessage = "$var cannot be less than $value."
    NotInstanceOfTypeMessage = "$var is not from type $type."
    NotValidEmailMessage = "$var is not a valid email."
    MinCountMessage = "$var must have at least $value elements."
    NotInfinityNumberMessage = "$var is not an infinity number."
    InfinityNumberMessage = "$var is an infinity number."
    NotNaNMessage = "$var is an NaN."
    NaNMessage = "$var is not an NaN."
    LengthNotGreaterThanMessage = "$var length cannot be greater than $value."
    LengthNotLessThanMessage = "$var length cannot be less than $value."
    NotInMessage = "Collection does not contain the $value."
    ContainDuplicatedMessage = "The collection have duplicated elements."
    NotWhitespaceMessage = "$var is not a whitespace."
    NotNegative = "$var is negative."
    EvenNumber = "$var is even"
    OddNumber = "$var is odd"
